version: '3.8'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - front_back
      - back_db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/melodia_db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - front_back
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: melodia_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - back_db
    restart: unless-stopped

volumes:
  pgdata:

networks:
  front_back:
  back_db:
